export default class RefData {}

RefData.LABELS = [
  { text: 'Status' },
  { text: 'Pipeline ID' },
  { text: 'Degree of Confidence' },
  { text: 'Termination date' },
  { text: 'Exposure status' },
  { text: 'Deal logged' },
  { text: 'Limits', type: 'section' },
  { text: '', type: 'limitsComponent' },
  { text: 'Products', type: 'section' },
  { text: '', type: 'productsComponent' },
  { text: 'Counterparties', type: 'section' },
  { text: '', type: 'counterpartiesComponent' },
  { text: 'Booking', type: 'section' },
  { text: '', type: 'bookingComponent' },
  { text: 'Collateral', type: 'section' },
  { text: '', type: 'collateralComponent' },
  { text: 'DE-Risking', type: 'section' },
  { text: '', type: 'deRiskingComponent' },
];

RefData.DEAL_LIMITS = [
  { element: 'select', colSize: 8 },
  { element: 'text', colSize: 6, optional: true },
  { element: 'select', colSize: 6 },
  { element: 'date', colSize: 6 },
  { element: 'select', colSize: 8 },
  { element: 'toogleButton', colSize: 12 },
  { element: '', type: 'section' },
  { element: 'limitsComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'productsComponent', type: '', productsAdded: false },
  { element: '', type: 'section' },
  { element: 'counterpartiesComponent', type: '', counterpartyAdded: true },
  { element: '', type: 'section' },
  { element: 'bookingComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'collateralComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'deRiskingComponent', type: '' },
];

RefData.DEAL_SUBLIMITS = [
  { element: 'select', colSize: 8 },
  { element: 'text', colSize: 6, optional: true },
  { element: 'select', colSize: 8 },
  { element: 'date', colSize: 6 },
  { element: 'select', colSize: 8 },
  { element: 'toogleButton', colSize: 12 },
  { element: '', type: 'section' },
  { element: 'limitsComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'productsComponent', type: '', productsAdded: true },
  { element: '', type: 'section' },
  { element: 'counterpartiesComponent', type: '', counterpartyAdded: false },
  { element: '', type: 'section' },
  { element: 'bookingComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'collateralComponent', type: '' },
  { element: '', type: 'section' },
  { element: 'deRiskingComponent', type: '' },
];